CREATE DATABASE SBRP_SCHEMA;
USE SBRP_SCHEMA;

CREATE TABLE STAFF
(STAFF_ID		int				not null,
STAFF_FNAME		varchar(50)		not null,
STAFF_LNAME		varchar(50)		not null,
DEPT			varchar(50)		not null,
COUNTRY			varchar(50)		not null,
EMAIL			varchar(50)		not null,
CONSTRAINT STAFF_PK PRIMARY KEY (STAFF_ID));

CREATE TABLE STAFF_ACCESS
(STAFF_ID		int		not null,
ACCESS_RIGHTS	int		not null,
CONSTRAINT STAFF_ACCESS_PK PRIMARY KEY (STAFF_ID),
CONSTRAINT STAFF_ACCESS_FK1 FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID));

CREATE TABLE STAFF_SKILL
(STAFF_ID		int				not null,
SKILL_NAME		varchar(50) 	not null,
CONSTRAINT STAFF_SKILL_PK PRIMARY KEY (STAFF_ID, SKILL_NAME),
CONSTRAINT STAFF_SKILL_FK1 FOREIGN KEY (STAFF_ID) REFERENCES STAFF(STAFF_ID));

CREATE TABLE ROLE_SKILL
(ROLE_NAME		varchar(20) 	not null,
SKILL_NAME		varchar(50) 	not null,
CONSTRAINT ROLE_SKILL_PK PRIMARY KEY (ROLE_NAME, SKILL_NAME));

CREATE TABLE STAFF_ROLE_SKILL
(STAFF_ID		int				not null,
ROLE_NAME		varchar(20) 	not null,
SKILL_NAME		varchar(50) 	not null,
CONSTRAINT STAFF_ROLE_SKILL_PK PRIMARY KEY (STAFF_ID),
CONSTRAINT STAFF_ROLE_SKILL_FK1 FOREIGN KEY (STAFF_ID, SKILL_NAME) REFERENCES STAFF_SKILL(STAFF_ID, SKILL_NAME),
CONSTRAINT STAFF_ROLE_SKILL_FK2 FOREIGN KEY (ROLE_NAME, SKILL_NAME) REFERENCES ROLE_SKILL(ROLE_NAME, SKILL_NAME));

CREATE TABLE ROLE_LISTING
(ROLE_ID					int				not null	auto_increment,
ROLE_NAME					varchar(20) 	not null,
JOB_TYPE					varchar(50) 	not null,
DEPARTMENT					varchar(50) 	not null,
JOB_DESCRIPTION				varchar(50) 	not null,
ORIGINAL_CREATION_DT		datetime		not null,
EXPIRY_DT					datetime 		not null,
HIRING_MANAGER_ID			int			 	not null,
CONSTRAINT ROLE_LISTING_PK PRIMARY KEY (ROLE_ID),
CONSTRAINT ROLE_LISTING_FK1 FOREIGN KEY (HIRING_MANAGER_ID) REFERENCES STAFF(STAFF_ID));

CREATE TABLE APPLICATION
(APPLICATION_ID				int				not null	auto_increment,
APPLICANT_STAFF_ID			int 			not null,
APPLICANT_EXISTING_ROLE		varchar(50) 	not null,
APPLICANT_EXISTING_DEPT		varchar(50) 	not null,
APPLICATION_STATUS			varchar(20)	 	not null,
DATE_APPLIED				datetime	 	not null,
APPLIED_ROLE_ID				int 			not null,
CONSTRAINT APPLICATION_PK PRIMARY KEY (APPLICATION_ID),
CONSTRAINT APPLICATION_FK1 FOREIGN KEY (APPLICANT_STAFF_ID) REFERENCES STAFF(STAFF_ID),
CONSTRAINT APPLICATION_FK2 FOREIGN KEY (APPLIED_ROLE_ID) REFERENCES ROLE_LISTING(ROLE_ID));

CREATE TABLE APPLICATION_SKILLS
(APPLICATION_ID				int				not null,
APPLICANT_SKILLS			varchar(50) 	not null,
CONSTRAINT APPLICATION_SKILLS_PK PRIMARY KEY (APPLICATION_ID),
CONSTRAINT APPLICATION_SKILLS_FK1 FOREIGN KEY (APPLICATION_ID) REFERENCES APPLICATION(APPLICATION_ID));

CREATE TABLE ROLE_LISTING_SKILLS
(ROLE_ID				int				not null,
SKILLS					varchar(50) 	not null,
SKILLS_PROFICIENCY		int			 	not null,
CONSTRAINT ROLE_SKILLS_PK PRIMARY KEY (ROLE_ID),
CONSTRAINT ROLE_SKILLS_FK1 FOREIGN KEY (ROLE_ID) REFERENCES ROLE_LISTING(ROLE_ID));

#DROP SCHEMA SBRP_SCHEMA;

