USE SBRP_SCHEMA;
INSERT INTO STAFF VALUES (1, "JOHN", "TAN", "TESTDEPT", "SINGAPORE", "test@spmg5t5.com") ;
INSERT INTO STAFF VALUES (2, "CELESTE", "TAN", "TESTDEPT", "SINGAPORE", "test2@spmg5t5.com") ;
INSERT INTO STAFF_ACCESS VALUES (1, 1) ;
