USE SBRP_SCHEMA;
DELETE FROM ROLE_LISTING;
ALTER TABLE ROLE_LISTING AUTO_INCREMENT = 1;

INSERT INTO ROLE_LISTING VALUES (null, 0, "TEST1", "FT", "ACCOUNTING STAFF", "SAMPLE DESCRIPTION",  CURRENT_TIMESTAMP , CURRENT_TIMESTAMP + 100000, 1, 1, CURRENT_TIMESTAMP) ;
INSERT INTO ROLE_LISTING VALUES (null, 0, "TEST2", "FT", "HR MANAGER", "SAMPLE DESCRIPTION",  CURRENT_TIMESTAMP , CURRENT_TIMESTAMP + 100000, 1, 1, CURRENT_TIMESTAMP) ;
INSERT INTO ROLE_LISTING VALUES (null, 0, "TEST3", "PT", "HR MANAGER", "SAMPLE DESCRIPTION",  CURRENT_TIMESTAMP , CURRENT_TIMESTAMP + 100000, 2, 2, CURRENT_TIMESTAMP) ;
INSERT INTO ROLE_LISTING VALUES (null, 0, "TEST4", "PT", "ACCOUNTING STAFF", "SAMPLE DESCRIPTION",  CURRENT_TIMESTAMP , CURRENT_TIMESTAMP + 100000, 3, 3, CURRENT_TIMESTAMP) ;
INSERT INTO ROLE_LISTING VALUES (null, 0, "TEST5", "FT", "SECRETARY", "SAMPLE DESCRIPTION",  CURRENT_TIMESTAMP , CURRENT_TIMESTAMP + 100000, 2, 2, CURRENT_TIMESTAMP) ;
INSERT INTO ROLE_LISTING VALUES (1, 1, "TEST1", "FT", "ACCOUNTING STAFF", "UPDATED DESCRIPTION",  CURRENT_TIMESTAMP , CURRENT_TIMESTAMP + 100000, 1, 2, CURRENT_TIMESTAMP + 50000) ;
