USE SBRP_SCHEMA;
DELETE FROM ROLE_LISTING;
ALTER TABLE ROLE_LISTING AUTO_INCREMENT = 1;

INSERT INTO ROLE_LISTING VALUES (null, "TEST1", "FT", "ACCOUNTING STAFF", "SAMPLE DESCRIPTION",  CURRENT_TIMESTAMP , CURRENT_TIMESTAMP + 100000, 1) ;
INSERT INTO ROLE_LISTING VALUES (null, "TEST2", "FT", "HR MANAGER", "SAMPLE DESCRIPTION",  CURRENT_TIMESTAMP , CURRENT_TIMESTAMP + 100000, 1) ;
INSERT INTO ROLE_LISTING VALUES (null, "TEST3", "PT", "HR MANAGER", "SAMPLE DESCRIPTION",  CURRENT_TIMESTAMP , CURRENT_TIMESTAMP + 100000, 2) ;
INSERT INTO ROLE_LISTING VALUES (null, "TEST4", "PT", "ACCOUNTING STAFF", "SAMPLE DESCRIPTION",  CURRENT_TIMESTAMP , CURRENT_TIMESTAMP + 100000, 3) ;
INSERT INTO ROLE_LISTING VALUES (null, "TEST5", "FT", "SECRETARY", "SAMPLE DESCRIPTION",  CURRENT_TIMESTAMP , CURRENT_TIMESTAMP + 100000, 2) ;
