USE SBRP_SCHEMA;
DELETE FROM STAFF_ACCESS;
DELETE FROM STAFF;
INSERT INTO STAFF VALUES (1, "JOHN", "LIM", "TESTADMIN_DEPT", "SINGAPORE", "admin@spm.com") ;
INSERT INTO STAFF VALUES (2, "CELESTE", "TAN", "TESTMGR_DEPT", "SINGAPORE", "manager@spm.com") ;
INSERT INTO STAFF VALUES (3, "PETER", "LEE", "TESTSTF_DEPT", "SINGAPORE", "staff@spm.com") ;
INSERT INTO STAFF VALUES (4, "MARY", "ANNE", "TESTDEPT", "SINGAPORE", "noaccess@spm.com") ;

INSERT INTO STAFF_ACCESS VALUES (1, 3) ;
INSERT INTO STAFF_ACCESS VALUES (2, 2) ;
INSERT INTO STAFF_ACCESS VALUES (3, 1) ;